apiVersion: apps/v1
kind: Deployment
metadata:
  name: koolna-webui
  namespace: koolna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koolna-webui
  template:
    metadata:
      labels:
        app: koolna-webui
    spec:
      serviceAccountName: koolna-webui
      containers:
        - name: webui
          image: ghcr.io/buvis/koolna-webui:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
