apiVersion: v1
kind: ServiceAccount
metadata:
  name: koolna-webui
  namespace: koolna
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koolna-webui
  namespace: koolna
rules:
  - apiGroups: ["koolna.buvis.net"]
    resources: ["koolnas"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: koolna-webui
  namespace: koolna
subjects:
  - kind: ServiceAccount
    name: koolna-webui
    namespace: koolna
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koolna-webui
