apiVersion: koolna.buvis.net/v1alpha1
kind: Koolna
metadata:
  labels:
    app.kubernetes.io/name: koolna-operator
    app.kubernetes.io/managed-by: kustomize
  name: koolna-sample
spec:
  # TODO(user): Add fields here
